### ISSUE TITLE
ride request didn't work

### ISSUE THREAD

**Issue by hamza176** [Nirvan66/DeRiS#1]
jobs not get posted to driver

**Comment by ManishankarGoswami** [comment]
have you resolved the issue @hamza176

**Comment by ManishankarGoswami** [comment]
@hamza176  where was the error in the code ,i am getting the same problem.please reply

**Comment by ManishankarGoswami** [comment]
@hamza176  please contact me -manisankargoswami@gmail.com

**Comment by hamza176** [comment]
you can tell me your problem ill try to help you if I could
